### ISSUE TITLE
Parent - Add Child  Profile - See Their Info

### ISSUE THREAD

**Issue by gsledbetter** [BitBrill/loco-family#1]
### User Story
As a parent, I want to be able to add a child so that I can see their information in the app and track their location.

### Sub-Tasks
- [ ] Add child's first and last name #3
- [ ] Add child's birthdate #4
- [ ] Add child's photo #6
- [ ] Add child's phone number #5

### AC
